[build]
  command = "npm run build"
  publish = "out" # For static export. Use `.next` for SSR

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
