import { test, expect } from '@playwright/test';

test('testing the performance feedback page', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('button', { name: 'Advanced Modules ▼' }).click();
  await page.getByTestId('nav-performance-feedback').click();
  await page.waitForTimeout(1000);
  await page.getByRole('checkbox', { name: 'Only show products in stock' }).check();
  await page.getByTestId('search-input').click();
  await page.getByTestId('search-input').fill('pear');
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.getByTestId('search-input').click();
  await page.getByTestId('search-input').fill('');
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Beverages' }).click();
  await page.getByRole('row', { name: 'Tea 80 $4 Add to Cart' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Water 14 $10 Add to Cart' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Milkshake 45 $12 Add to Cart' }).getByRole('button').click();
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Meat' }).click();
  await page.getByRole('row', { name: 'Turkey 64 $16 Add to Cart' }).getByRole('button').click();
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Snacks' }).click();
  await page.getByRole('row', { name: 'Nuts 43 $11 Add to Cart' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Popcorn 6 $5 Add to Cart' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Crackers 78 $6 Add to Cart' }).getByRole('button').click();
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Bakery' }).click();
  await page.getByRole('row', { name: 'Croissant 46 $5 Add to Cart' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Croissant 70 $5 Add to Cart' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Muffin 80 $12 Add to Cart' }).getByRole('button').click();
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Seafood' }).click();
  await page.getByRole('row', { name: 'Tuna 97 $1 Add to Cart' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Cod 87 $4 Add to Cart' }).getByRole('button').click();
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'All' }).click();
  await page.getByRole('button', { name: '7' }).click();
  await page.getByRole('button', { name: 'Previous' }).click();
  await page.getByRole('button', { name: 'Previous' }).click();
  await page.getByRole('button', { name: 'Previous' }).click();
  await page.getByRole('button', { name: 'Previous' }).click();
  await page.getByRole('row', { name: 'Passionfruit 96 $19 Add to' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Passionfruit 96 $19 Add to' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Passionfruit 96 $19 Add to' }).getByRole('button').click();
  await page.waitForTimeout(1000);
  await page.locator('div > .lucide').click();
  await page.getByText('Your Cart14').click();
  await page.waitForTimeout(1000);
  await page.getByRole('checkbox', { name: 'Only show products in stock' }).uncheck();
  await page.getByRole('row', { name: 'Juice 48 $3 Add to Cart' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Juice 48 $3 Add to Cart' }).getByRole('button').click();
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Dairy' }).click();
  await page.getByRole('row', { name: 'Yogurt 46 $19 Add to Cart' }).getByRole('button').click();
  await page.locator('form').click();
  await page.getByRole('checkbox', { name: 'Only show products in stock' }).check();
  await page.getByRole('row', { name: 'Milk 10 $6 Add to Cart' }).getByRole('button').click();
  await page.getByRole('row', { name: 'Cheese 83 $17 Add to Cart' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
});